#!/bin/bash

. "$(dirname $0)/_/husky.sh"

## List changed files
STATUS=$(git status --porcelain)
STAGED=$(echo "$STATUS" | grep -E '^(M|A|D|R|C) ' | sed -E 's/^(M|A|D|R|C)  ([^ ]+).*$/\2/g')
#MODIFIED=$(echo "$STATUS" | grep -E '^ (M|A|D|R|C)' | sed -E 's/^ (M|A|D|R|C) ([^ ]+).*$/\2/g')
#UNTRACKED=$(echo "$STATUS" | grep -E '^??' | sed -E 's/^?? //g')
#CHANGED=$(echo "$STAGED" && echo "$MODIFIED" && echo "$UNTRACKED")

## Check for ongoing merge
MERGE=$(git rev-parse -q --verify MERGE_HEAD || echo "")
M_MSG=$([[ -f .git/MERGE_MSG ]] && cat .git/MERGE_MSG || echo '')

## Check for empty commits
if [[ -z "$STAGED" && -z "$MERGE" ]] ; then 
    
    echo "[COMMIT-MSG Hook] No staged changes && no ongoing merge => aborting commit"
    exit 1

fi

## Lint commit message
echo "[COMMIT-MSG Hook] Linting commit message" && pnpm commitlint --edit $1
