# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
 push:
   branches:
     - develop
  # release:
    # types: [created]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 10
  #     - run: yarn install
  #     - run: yarn run build
      # - run: npm test

  publish-gpr:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: yarn run build
      - run: npm publish dist/dgt-shared-test
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm publish dist/dgt-shared-utils
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm publish dist/dgt-shared-data
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm publish dist/dgt-shared-web
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm publish dist/dgt-shared-connectors
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
